-- run this in your Supabase SQL Editor
ALTER TABLE shots ADD COLUMN IF NOT EXISTS session_id UUID REFERENCES sessions(session_id);
ALTER TABLE shots ADD COLUMN IF NOT EXISTS team_id UUID REFERENCES teams(team_id);
ALTER TABLE shots ADD COLUMN IF NOT EXISTS round_number INT DEFAULT 1;
ALTER TABLE shots ADD COLUMN IF NOT EXISTS make_value INT;
ALTER TABLE shots ADD COLUMN IF NOT EXISTS location_value INT;
ALTER TABLE shots ADD COLUMN IF NOT EXISTS points INT;
ALTER TABLE shots ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT now();

ALTER TABLE teams ADD COLUMN IF NOT EXISTS round_1_finished BOOLEAN DEFAULT false;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS round_2_finished BOOLEAN DEFAULT false;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS banned_zone INT;
